language: python

python:
- '3.7'

matrix:
  include:
    - python: 3.10.2
      dist: xenial

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

script:
  - flake8
  - coverage run -m pytest

# Don't compile "experimental" branches starting with x-, y-, or z-.
branches:
  except:
    - /^x-.*$/
    - /^y-.*$/
    - /^z-.*$/
