[tool.doks]
auto = true

[tool.poetry]
name = "nmr"
version = "0.9.2"
description = "🌐 Name all canonical things 🌐"
authors = ["Tom Ritchford <tom@swirly.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
datacls = "^4.5.0"
dtyper = "^2.0.0"
lat-lon-parser = "^1.3.0"
typer = "^0.7.0"
chess = "^1.9.3"

[tool.poetry.group.dev.dependencies]
coverage = "^6.5.0"
doks = "^1.0.1"
flake8 = "^5.0.4"
pytest = "^7.2.0"


[tool.coverage]
[tool.coverage.run]
branch = "True"
source = "num_name"

[tool.coverage.report]
fail_under = "100"
skip_covered = "True"
exclude_lines = ["pragma: no cover", "if False:", "if __name__ == .__main__.:", "raise NotImplementedError"]

[tool.mypy]
strict = true
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
